server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pet_service?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml # 可选，如果纯注解可以省略
  type-aliases-package: com.imis.petmanagebackend.entity
  global-config:
    db-config:
      id-type: auto

file:
  upload-path: d:\pet-platform\pet-manage-backend\upload

tencent:
  cos:
    secret-id: ${COS_SECRET_ID}               # 替换为你的 SecretId
    secret-key: ${COS_SECRET_KEY}             # 替换为你的 SecretKey
    region: ap-guangzhou                      # 替换为你的 Bucket 地域
    bucketName: cthulhu-1400035022            # 替换为你的 Bucket 名称
    baseUrl: https://cthulhu-1400035022.cos.ap-guangzhou.myqcloud.com # 访问域名前缀